### ISSUE TITLE
(Delete)Food Collection Delete 

### ISSUE THREAD

**Issue by MarkyAaronYoung** [nss-evening-cohort-12/nutshell-alces#10]
# User Story
As a user, I should be able to delete items on the menu.

# AC
**WHEN** a user is logged in
**AND** is on the food page
**THEN** they will see a delete button on each food item
**AND** when clicked it'll remove the food item locally 
**AND** when clicked it'll remove the food item from firebase

# Dev Notes
* Create a food collection div
* Addclass.hide unless the user is logged in
* Create deleteFood() -- ```src/javascripts/components/deleteFood/deleteFood.js```
* ```$('body'). on('click', '.delete-food', deleteFood)```
* Use ```axios.delete()``` to remove food from firebase. -- ```src/javascripts/helpers/data/foodData.js```
* create ```axios.delete``` commands to firebase to allow data to be deleted

**Comment by MarkyAaronYoung** [comment]
<img width="254" alt="Screen Shot 2020-07-14 at 7 20 08 PM" src="https://user-images.githubusercontent.com/62973018/87488874-1b1a4a80-c607-11ea-9e9c-d4c49c761b50.png">

**Comment by luketlancaster** [comment]
which axios method will you use?

**Comment by luketlancaster** [comment]
so I'll see the delete button anywhere, so long as I'm logged in? i.e. AC needs some clarification: when the user is authenticated, and on the food page, I'll see a delete button on each item, etc etc etc

**Comment by luketlancaster** [comment]
If the delete creates a modal for verification or something a new module is good. But if there’s no verification, you can probably keep this functionality in the foodList module
