### ISSUE TITLE
ERD

### ISSUE THREAD

**Issue by MarkyAaronYoung** [nss-evening-cohort-12/nutshell-alces#11]

**Comment by MarkyAaronYoung** [comment]
<img width="521" alt="PanAm3ERD" src="https://user-images.githubusercontent.com/62973018/87372603-9c150b80-c54d-11ea-825f-056de7a7e2a2.png">

**Comment by luketlancaster** [comment]
1. Looks pretty good!
1. Can you add a `lastServiced` to airplanes that'll be a timestamp you can display all pretty like.
1. Can you add a `isAvailable` or `isSoldOut` boolean to the food table? So you'll display a note that the item is sold out/update with a radio button.

**Comment by MarkyAaronYoung** [comment]
Updated ERD
<img width="579" alt="Screen Shot 2020-07-14 at 6 19 57 PM" src="https://user-images.githubusercontent.com/62973018/87485567-b6f38880-c5fe-11ea-928d-eed96301542a.png">
