### ISSUE TITLE
Crew Collection Tickets

### ISSUE THREAD

**Issue by luketlancaster** [nss-evening-cohort-12/nutshell-alces#5]
# User Stories
- [x] As a user, I should be able to view all crew members on the team.
- [x] As a user, I should be able to add a crew member to the team.
- [x] As a user, I should be able to edit a crew member on the team.
- [x] As a user, I should be able to remove a crew member from the team.

**Comment by MarkyAaronYoung** [comment]
<img width="604" alt="PanAmCrew" src="https://user-images.githubusercontent.com/62973018/87471610-463f7280-c5e4-11ea-8715-148361da0060.png">
