### ISSUE TITLE
View All Planned Flights

### ISSUE THREAD

**Issue by jeaninedavis** [nss-evening-cohort-12/nutshell-alces#57]
# User Story
As a user, I should be able to view all planned flights.

# AC
**WHEN** the user navigates to the flights dashboard from a button in the navbar
**THEN** they will see a page that displays summary cards for each of the existing flights
**AND** if they click on a card it takes them to a single flight view with all of the flight details (#64)
**AND** there will also be a visible button that they can click if they want to create a new flight

# Dev Notes
* make a `flightMaker.js` file to house the `const buildFlight` function that makes the card-builder domString 
* make a `flightsList.js` file and `const seeFlights` function to call the `buildFlight` function
* use a `forEach` loop to display all the flights
![image](https://user-images.githubusercontent.com/62957170/88461779-2e7daf00-ce6c-11ea-8e33-ecaea813f9a3.png)

**Comment by luketlancaster** [comment]
we discussed this a bit. But to make your life easier you _could_ remove any information that needs a join table and only display the "bare minimum," and if a user wants more information they need to click through to the "view single flight" view

**Comment by jeaninedavis** [comment]
@luketlancaster I think we're going to end up doing that, still need to change the wireframe to reflect it
