### ISSUE TITLE
Add Crew Members to Flight

### ISSUE THREAD

**Issue by jeaninedavis** [nss-evening-cohort-12/nutshell-alces#59]
# User Story
As a user, I should be able to add crew members to a flight.

# AC
**WHEN** I am building a new flight on the website I should see the option to add crew members
**THEN** I should be able to choose which crew to add to the flight.
**AND** I should be required to have 6 crew on a flight

# Dev Notes
* create a flightCrew join table for adding to the flight.
```js
"flightCrew1": {
    "flightId": "flight1"
    "crewId": "crew1"
}
```
* use`axios.post()` to push the value to the database
* use a smash function to join the`flightCrew.json` file with the `flight.json` table...
* it should look something like this?
```js
/**
  * 1. get all flights
  * 2. get all crew
  * 3. get all flightCrew
  * 4. make the data structure
  * 5.
  * 6. resolve the data we've made
  * 7. reject any err
*/
const getFlightsWithCrew = () => new Promise((resolve, reject) => {
  flightData.getFlights()
    .then((allFlights) => {
      CrewData.getCrew().then((allCrew) => {
        flightCrewData.getAllFlightCrew().then((allFlightCrew) => {
          const finalCrew = [];
          // loop over each flight
          allFlights.forEach((oneFlight) => {
            // add each crew to oneFlight
            const flight = { crew: [ ], ...oneFlight };
            // ^^ ...oneFlight adds all the keys and values of oneFlight to this new object

            // find all FlightCrew for the current flight
            const flightCrewOwners = allFlightCrew.filter((flightCrew) => flightCrew.flightId === flight.id);

            allCrew.forEach((oneCrew) => {
              const  crew = { ...oneCrew };
              // add oneCrew isChecked if oneCrew owns flight
              const isOwner = flightCrewOwners.find((flightCrew) => flightCrew.crewId === crew.id);

              crew.isChecked = isOwner !== undefined;
              crew.flightCrewId = isOwner ? isOwner.id : `no-${flight.id}-${crew.id}`;
              /* ^^
                this is a ternary operation and it works like an if statement:
                if (isOwner) {
                  return isOnwer.id
                } else {
                  return `no-${flight.id}-${crew.uid}`
                }
              */

              // add flightCrewId, faking id where needed
              flight.crew.push(crew);
              // ^^ adds each crew to the crew key in 'flight'
            });
            finalFlight.push(flight);
          });
          resolve(finalFlight);
        });
      });
    })
    .catch((err) => reject(err));
});
```
notes: then the smash function would ‘join’ the flight table with the flightCrew table?

Correct, “Gimme all the crew members for this flight, using the crew ids in the flightCrew table”

**Comment by wcampbell91** [comment]
@luketlancaster I stole this smash function from the firebase-mushrooms project. I think I correctly changed the values to reflect what we need to do with flights, crew, and flightCrew. Can you verify if I'm at least on the right track?

**Comment by luketlancaster** [comment]
on first blush that looks good to me @wcampbell91. Make sure to not Capitalize where you shouldn't be (`const Crew = ...` then doing `flight.crew.push(crew)`. Also change the name of the function 🙃 

goal of this function is the ability to show check marks, really similar to what we did with the Mycologists on the Mushroom cards right?

**Comment by wcampbell91** [comment]
Yeah I believe that's what we're trying to do with by showing the which crew is assigned to which flight. Good to know I'm at least headed in the right direction, and I definitely will change the name of the function haha

**Comment by luketlancaster** [comment]
so....just thinking about this. If you're going to have a page where you view only 1 Flight at a time, with all the appropriate details, your smash function can be a bit more simple...you can make a `flightCrewData.getFlightCrewByFlight(flightId)` data getter, and in that do your `orderBy` and `equalTo`...this way you're only ever fetching the FlightCrew for a specific flight

all depends on the implementation though. If you have a view that's all Flights with All The Details, you'll need what you created up above too
