### ISSUE TITLE
Foods Collection

### ISSUE THREAD

**Issue by luketlancaster** [nss-evening-cohort-12/nutshell-alces#6]
- [x] As a user, I should be able to view all the food options available for flights. 
- [x] As a user, I should be able to add items to the menu. 
- [x] As a user, I should be able to edit items on the menu.
- [x] As a user, I should be able to delete items on the menu.

**Comment by MarkyAaronYoung** [comment]
[Food Collection Main Page edit#7](https://github.com/nss-evening-cohort-12/nutshell-alces/issues/7)

**Comment by MarkyAaronYoung** [comment]
[Food Collection Add Items edit#8](https://github.com/nss-evening-cohort-12/nutshell-alces/issues/8)

**Comment by MarkyAaronYoung** [comment]
[Food Collection Edit Items edit#9](https://github.com/nss-evening-cohort-12/nutshell-alces/issues/9)

**Comment by MarkyAaronYoung** [comment]
[Food Collection Delete Items edit#10](https://github.com/nss-evening-cohort-12/nutshell-alces/issues/10)
