### ISSUE TITLE
Add Plane to Flight

### ISSUE THREAD

**Issue by jeaninedavis** [nss-evening-cohort-12/nutshell-alces#62]
# User Story
As a user, I should be able to add a plane to a flight.

# AC
**WHEN** the user is in the flight dashboard to create a new flight
**THEN** they should have an option to add a single plane to that flight from a list
**AND** all of the plane's information should get added to the flight as well to be visible in the single flight view

# Dev Notes
* use a `const getSingleFlightWithPlanes` new Promise function that takes the flight ID
* will need a `flight.planes =[]`
* structure similar to `getSingleMycoWithShrooms` and `const mycoMushroomController` from mushroom example?
* `const getMycoShroomsByShroomId` = `const getFlightPlanesByPlaneId`?
* remember a 1-1 relationship between flights and planes. `axios.post`to add the new plane to the flight
* click event to take planeId from item selected in dropdown and add it to the new flight being created

**Comment by jeaninedavis** [comment]
@luketlancaster I don't know if this is remotely headed down the right path. thoughts?

**Comment by luketlancaster** [comment]
yeah, really good start. So adding a Plane to a Flight would be doing a CREATE on the FlightPlane collection (or whatever you've called it)

**Comment by luketlancaster** [comment]
ok I think I was overthinking this one/misunderstood what you needed to do. 

A Flight can only ever have one Plane, right? So you'll be adding a `flight.planeId` to the flight, and doing an update to the flight object. You shouldn't need a join table/to add a `planes` array onto the flight object. But when you display you'll need to get the plane id, and then `getPlaneById` in your plane data or somesuch. Sorry for the misunderstanding 😩

does that make sense/feel like it makes your life easier?

**Comment by wcampbell91** [comment]
@luketlancaster Yeah that makes sense!

**Comment by jeaninedavis** [comment]
@luketlancaster do I need to remove the orderBy and equalTo part? is that not necessary for this one?

**Comment by luketlancaster** [comment]
yeah you won't need that because you can do a GET to `planes/${planeId}.json` if you need to get that specific plane, no need to query on a property in the plane object itself
