### ISSUE TITLE
Add Food to Flight

### ISSUE THREAD

**Issue by jeaninedavis** [nss-evening-cohort-12/nutshell-alces#63]
# User Story
As a user, I should be able to add food items to a flight 

# AC
**WHEN** the user is in the flight dashboard to create a new flight
**THEN** they should have an option to add foods to that flight
**AND** there will be a radio button for the user to select if the flight is international or domestic
**AND** the list of foods that populates will be either meals and snacks if international or snacks only if domestic

# Dev Notes
* use an if statement to populate the foods list based on whether the selected radio button is domestic or international
* create a `flightFoods.json` join table and a `flightFoodData.js` file
* use a smash function to join up the relationships between flightData and foodData
* `flightFoodData.getFlightFoodByFlightId`, then get all the food
* use `axios.post`, `orderBy`, and `equalTo` in flightFoodData
* structure the data in the `json` file like this:
```js
"flightFood1": {
    "flightId": "flight1"
    "foodId": "food1"
}
```

**Comment by jeaninedavis** [comment]
@luketlancaster here's another one I would appreciate your 👀 on please

**Comment by luketlancaster** [comment]
yeah this is a good start as well. Maybe a little more on the flow of the devnotes. In fact...I'd use a orderBy/equalTo to only fetch the foods that are domestic/international (based on which the flight is)...but I guess that might make the logic in setting this up more complex 🤔  something to think about


but overall this is the flow, yeah
