### ISSUE TITLE
(Read)Food Collection Main Page

### ISSUE THREAD

**Issue by MarkyAaronYoung** [nss-evening-cohort-12/nutshell-alces#7]
# User Story
As a user, I should be able to view all the food options available for flights.

# AC
**WHEN** I click on the Food button on the navbar
**THEN** I should see a display of photos of food
**AND** each photo will have a description including the name, type of food, and availability

# Dev Notes
* Create seed data food.json
* Create foodData,js, foodList.js, food.js
* import firebase database
* use axios.get to retrieve food data from firebase
* printToDom on click event
* add isAvailable boolean to food item
* if (isAvailable === true) {let domString += `${food.imgUrl}`else {let domString += `${circleCrossedOut.imgUrl}`}

**Comment by MarkyAaronYoung** [comment]
<img width="603" alt="FoodPanAm" src="https://user-images.githubusercontent.com/62973018/87372199-98cd5000-c54c-11ea-9f5a-edbdf203ef19.png">

**Comment by luketlancaster** [comment]
what data files will you need? What methods will be exported from there? Link to examples from another repo maybe?

**Comment by luketlancaster** [comment]
AC needs a bit of work. "When I load the page" probably isn't right? Or does this view get loaded on pageload. I guess I assumed you'd see it from clicking on a button/element somewhere else? Like a navbar or something?
