### ISSUE TITLE
Create flight foods join table

### ISSUE THREAD

**Issue by wcampbell91** [nss-evening-cohort-12/nutshell-alces#72]
# User Story
As a dev I should be able to use a join table to add foods to a flight

# AC
**WHEN** I visit the create flight page, I should be able to add foods to flights
**AND** I will need a join data table to do this
**AND** This table will update the `flights.json` file
**AND** be viewable on the single flight view page

# Dev Notes
* create a `flightFoods.json` file
```json 
"flightFood1": {
    "foodId": "food1",
    "flightId": "flight1",
}
```
* create a `flightFoodData.js` file with CRUD functions
```js
const getFlightFoods = () => new Promise((resolve, reject) => {
    axios.get(`${baseUrl}/flightFoods.json`)
        .then((response) => {
            const flightFoodsObjects = response.data;
            const flightFoods = [];
            Object.keys(flightFoodsObjects).forEach((flightFoodsId) => {
                flightFoodsObjects[flightFoodsId].id = flightFoodsId;
                flightFoods.push(flightFoodsObjects[flightFoodsId]);
            });
            resolve(flightFoods); 
        })
        .catch((err) => reject(err));
});

const getFlightFoodsById = (flightFoodsId) => axios.get(`{baseUrl}/flightFoods/${flightFoodsId}.json`);

const deleteFlightFoods = (flightFoodsId) => axios.delete(`${baseUrl}/flightFoods/${flightFoodsId}.json`);

const addFlightFoods = (newFlightFoodsObj) => axios.post(`${baserUrl}/flightFoods.json`, newFlightFoodsObj);
```

**Comment by luketlancaster** [comment]
> As a user I should be able to use a join table to add foods to a crew

add foods to a flight?

which page are you adding this to?

AC needs some love 😄 

also this should probably be "as a dev..." user stories, since your user is never going to use the code directly, right?
