### ISSUE TITLE
Create Flight Plane Div

### ISSUE THREAD

**Issue by jeaninedavis** [nss-evening-cohort-12/nutshell-alces#76]
# User Story
As a user, I need to see a section in the "create flight" dashboard that will allow me to add a plane to a flight

# AC
**WHEN** the user navigates to the create flight dashboard
**THEN** they should see a layout with different components to add to the flight
**AND** in the upper right-hand section should be a section with a dropdown where the user can select a single plane

# Dev Notes
* #62 contains the code instructions for adding the plane to the flight database
* include in the css to get this in the right position on the page
```css
  position: absolute;
  right: 0;
  width: 50%;
  height: 50%;
```
* Create a `<div id="planes"></div>` in the `<div id="flightDashboardContainer>`
* Use bootstrap dropdown and a `forEach` that shows all the planes
* Grab the `planeId` from the item selected from the dropdown
* `utils.printToDom('#planes', domString)`

<img width="686" alt="Screen Shot 2020-07-23 at 6 50 16 PM" src="https://user-images.githubusercontent.com/62917622/88350209-0b41eb00-cd18-11ea-93f7-ab3652681929.png">

**Comment by luketlancaster** [comment]
AC 👀

**Comment by jeaninedavis** [comment]
oops, thanks 😂

**Comment by jeaninedavis** [comment]
@luketlancaster AC is there now

**Comment by luketlancaster** [comment]
looks good!
