### ISSUE TITLE
(Create)Food Collection Add Items

### ISSUE THREAD

**Issue by MarkyAaronYoung** [nss-evening-cohort-12/nutshell-alces#8]
# User Story
As a user, I should be able to add items to the menu.
# AC
**WHEN** a user is logged in and on the Food Collection Page
**THEN** they will see a single add button on the top of the page
**WHEN** clicked it'll populate a form where the user can add the name, type, and availability of food
**THEN** when submitted it'll add the food and dom will be reprinted with added food item.

# Dev Notes
* Create a food collection div 
* Create a single ```addFood button```
* Addclass.hide unless the user is logged in
* Create ```addFoodForm()``` use bootstrap form [bootstrap form](https://getbootstrap.com/docs/4.4/components/forms/)
* ```src/javascripts/component/addfoodForm/addfoodForm.js```
* ```$('body').on('click', '.add-food-form', addFoodForm)```
* Form will print to #new-food div using utils.printToDom('#new-food, domString); function
* Create ```addFood()``` that takes values from form and creates new food object
* ```$('body').on('click', '.submit-food-form', addFood)```
* ```* create ```axios.post()``` commands to firebase to add to data

**Comment by MarkyAaronYoung** [comment]
<img width="254" alt="Screen Shot 2020-07-14 at 7 20 08 PM" src="https://user-images.githubusercontent.com/62973018/87488899-32593800-c607-11ea-871a-b5a1bc4738c9.png">

**Comment by luketlancaster** [comment]
which axios method will you use?

**Comment by luketlancaster** [comment]
same here. Update AC.

So there's an add button on each food item? Or just one on the "main" food page?

**Comment by luketlancaster** [comment]
Maybe make your addFoodForm it’s own module
