### ISSUE TITLE
(Update)Food Collection Edit Items

### ISSUE THREAD

**Issue by MarkyAaronYoung** [nss-evening-cohort-12/nutshell-alces#9]
# User Story
As a user, I should be able to edit items to the menu.

# AC
**WHEN** a user is logged in and on the Food Collection Page
**THEN** they will see an edit button on the individual Food cards
**WHEN** clicked it'll populate a form the the user to edit the name, type, and availability of food
**THEN** when submitted it'll update the food and dom will be reprinted with updated food item.

# Dev Notes
* Add ```edit button``` to food cards
* Addclass.hide unless the user is logged in
* Create a food collection div
* Create editFoodForm() - Use bootsrap form
* ```$('body').on('click', '.edit-food-form', editFoodForm)```
* ```src/javascripts/components/editFoodForm/editFoodForm.js```
* Create editFood() that takes values from form and updates the food src/javascripts/components/editFood/editFood.js
* ```$('body').on('click', '.submit-edit-food-form', editFood)```
* Use axios.put() to update food in Firebase -- src/javascripts/helpers/data/foodData.js

**Comment by MarkyAaronYoung** [comment]
<img width="254" alt="Screen Shot 2020-07-14 at 7 20 08 PM" src="https://user-images.githubusercontent.com/62973018/87488892-2a00fd00-c607-11ea-9581-53edef1ccfba.png">

**Comment by luketlancaster** [comment]
which axios method will you use?

**Comment by luketlancaster** [comment]
how do I, as the user, actually edit the items? Does a form show up? Or something else? Need AC/dev notes around that info

**Comment by luketlancaster** [comment]
Same here, new module for form
